In [2]:
import torch

In [5]:
t = torch.rand(4,3,2)
p = torch.rand(3,2)

In [7]:
t.repeat(4)

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

In [75]:
o = torch.randint(0,2,(2,3,4))
new_o = o
o,new_o

(tensor([[[0, 1, 0, 1],
          [1, 0, 0, 1],
          [0, 1, 1, 0]],
 
         [[0, 0, 1, 1],
          [0, 1, 0, 1],
          [0, 1, 0, 0]]]),
 tensor([[[0, 1],
          [1, 0],
          [0, 1]],
 
         [[0, 1],
          [0, 1],
          [1, 0]],
 
         [[0, 0],
          [0, 1],
          [0, 1]],
 
         [[1, 1],
          [0, 1],
          [0, 0]]]))

In [78]:
einops.rearrange(o,'b c d -> (b h) c u',h=2,u=2)

EinopsError:  Error while processing rearrange-reduction pattern "b c d -> (b h) c u".
 Input tensor shape: torch.Size([2, 3, 4]). Additional info: {'h': 2, 'u': 2}.
 Identifiers only on one side of expression (should be on both): {'d', 'h', 'u'}

In [102]:
import torch
import einops
import torch.nn as nn
import torch.nn.functional as F

queries = torch.rand(1,2,4)
keys = torch.rand(1,3,4)
values = torch.rand(1,3,4)
head_size = 2
num_heads = 2
q_batch_size,q_context_len, hidden_size = queries.shape
kv_batch_size,kv_context_len, hidden_size = keys.shape

In [103]:
Q,K,V = nn.Linear(hidden_size,hidden_size,bias=False),nn.Linear(hidden_size,hidden_size,bias=False),nn.Linear(hidden_size,hidden_size,bias=False)


q = Q(queries)
q = q.transpose(0,1).contiguous().view(q_context_len,q_batch_size*num_heads,head_size).transpose(0,1).contiguous() #view(q.shape[0]*self.num_heads, self.hidden_size,self.head_size )


k = K(keys)
k = k.transpose(0,1).contiguous().view(kv_context_len,kv_batch_size*num_heads,head_size).transpose(0,1).contiguous() #view(q.shape[0]*self.num_heads, self.hidden_size,self.head_size )

v = V(values)
v = v.transpose(0,1).contiguous().view(kv_context_len,kv_batch_size*num_heads,head_size).transpose(0,1).contiguous() #view(q.shape[0]*self.num_heads, self.hidden_size,self.head_size )



In [104]:
q,k,v

(tensor([[[-0.4568, -0.4133],
          [-0.4059, -0.5416]],
 
         [[ 0.3154,  0.5734],
          [ 0.0683,  0.5658]]], grad_fn=<CloneBackward0>),
 tensor([[[-0.0158,  0.0611],
          [-0.0396, -0.0120],
          [ 0.0253, -0.1597]],
 
         [[-0.3343,  0.2251],
          [-0.3991,  0.0953],
          [-0.4120, -0.0413]]], grad_fn=<CloneBackward0>),
 tensor([[[-0.5666,  0.1705],
          [-0.4925,  0.0933],
          [-0.3296,  0.2364]],
 
         [[-0.0453,  0.1259],
          [-0.0343,  0.1458],
          [-0.0801,  0.3564]]], grad_fn=<CloneBackward0>))

In [105]:
mask = torch.tril(attention)
attention[mask==0] = -float('inf')
attention

tensor([[[1.0000,   -inf,   -inf],
         [0.6290, 0.3710,   -inf]],

        [[1.0000,   -inf,   -inf],
         [0.4855, 0.5145,   -inf]],

        [[1.0000,   -inf,   -inf],
         [0.4677, 0.5323,   -inf]],

        [[1.0000,   -inf,   -inf],
         [0.5466, 0.4534,   -inf]]], grad_fn=<IndexPutBackward0>)

In [106]:
attention = torch.bmm(q,k.transpose(-2,-1)) 
mask = torch.tril(attention)
attention[mask==0] = -float('inf')
attention = F.softmax(attention,dim=-1)
attention

tensor([[[1.0000, 0.0000, 0.0000],
         [0.4877, 0.5123, 0.0000]],

        [[1.0000, 0.0000, 0.0000],
         [0.5195, 0.4805, 0.0000]]], grad_fn=<SoftmaxBackward0>)

In [107]:
-0.0764*0.3244 + 0.0004* 0.3340  -0.2605* 0.3416

-0.11363736

In [108]:
context = torch.bmm(attention,v)
context

tensor([[[-0.5666,  0.1705],
         [-0.5286,  0.1309]],

        [[-0.0453,  0.1259],
         [-0.0400,  0.1355]]], grad_fn=<BmmBackward0>)

tensor([[[-0.5666,  0.1705, -0.0453,  0.1259],
         [-0.5286,  0.1309, -0.0400,  0.1355]]], grad_fn=<TransposeBackward0>)

In [57]:
(torch.tensor([0.0614,  0.3348]) * torch.tensor([0.4157,  0.1569])).sum()

tensor(0.0781)

In [54]:
Q(queries)

tensor([[[ 0.0614,  0.3348,  0.3951, -0.0715],
         [-0.0674,  0.3227,  0.6149, -0.2674]]], grad_fn=<UnsafeViewBackward0>)